apiVersion: v1
kind: Service
metadata:
  name: andela-interview-api-service
spec:
  selector:
    app: andela-interview-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer